# Site settings
title: Singablues
email: maximehrbt@gmail.com
description: "Blog d'un étudiant français à Singapour : Anecdotes, voyages et rencontres en Asie du Sud Est"
baseurl: ""
url: "http://herbautmax.github.io/"
twitter_username: MaximeHerbaut
github_username:  herbautmax

# Build settings
markdown: kramdown
permalink: pretty

paginate: 2                   # le nombre d'articles à afficher par page
paginate_path: /page:num      # l'url générée pour la pagination


