# Site settings
title: Maxime Herbaut, Ingénieur Développeur wweb full stack
email: maximehrbt@gmail.com
description: "Blog d'un étudiant français à Singapour : Anecdotes, voyages et rencontres en Asie du Sud Est"
baseurl: ""
url: "http://localhost:4000/"
#url: "herbautmax.github.io/"
twitter_username: MaximeHerbaut
github_username:  herbautmax

# Build settings
markdown: kramdown
permalink: pretty

paginate: 6                   # le nombre d'articles à afficher par page
paginate_path: /page:num      # l'url générée pour la pagination
