# Site settings
title: Maxime Herbaut, Ingénieur Développeur web full stack
email: maxime-herbaut@orange.fr
description: "Développement de sites web : site vitrine, site e-commerce, blog,
              application interne par un ingénieur web full stack en auto entreprise"
baseurl: ""
url: "http://localhost:4000"
#url: "herbautmax.github.io"
twitter_username: MaximeHerbaut
github_username:  herbautmax

# Build settings
markdown: kramdown
permalink: pretty

paginate: 6                   # le nombre d'articles à afficher par page
paginate_path: /page:num      # l'url générée pour la pagination
