# Site settings
title: Singablues
email: maximehrbt@gmail.com
description: "Blog d'un étudiant français à Singapour : Anecdotes, voyages et rencontres en Asie du Sud Est"
baseurl: ""
url: "http://localhost:4000/"
twitter_username: MaximeHerbaut
github_username:  herbautmax

# Build settings
markdown: kramdown
permalink: pretty
